name: "Build"

on: workflow_dispatch

env:
  FLEX_VERSION: 2.6.4
  BISON_VERSION: 3.8.2

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run build
      run: perl build.pl
    - name: Create ZIP file
      run: |
        mkdir -p out
        powershell Compress-Archive -Path "out/flex-${{ env.FLEX_VERSION }}_bison-${{ env.BISON_VERSION }}" -DestinationPath "out/flex-${{ env.FLEX_VERSION }}_bison-${{ env.BISON_VERSION }}.zip"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flex-${{ env.FLEX_VERSION }}_bison-${{ env.BISON_VERSION }}-zip
        path: out/flex-${{ env.FLEX_VERSION }}_bison-${{ env.BISON_VERSION }}.zip
        retention-days: 1
        overwrite: true
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: nightly
        files: out/flex-${{ env.FLEX_VERSION }}_bison-${{ env.BISON_VERSION }}.zip
